# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='testblog_post',
            name='fenlei',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testblog.category'),
        ),
    ]
