# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0002_auto_20180428_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testblog_post',
            old_name='fenlei',
            new_name='category',
        ),
    ]
