# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0003_auto_20180428_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='testblog_post',
            name='tag',
            field=models.ManyToManyField(default='', to='testblog.tag'),
        ),
    ]
