# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0004_auto_20180429_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testblog_post',
            name='tag',
            field=models.ManyToManyField(to='testblog.tag'),
        ),
    ]
