# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0007_auto_20180429_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testblog_post',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testblog.Category'),
        ),
        migrations.AlterField(
            model_name='testblog_post',
            name='tag',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='testblog.Tag'),
        ),
    ]
