# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0008_auto_20180429_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testblog_post',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='testblog',
            field=models.ManyToManyField(to='testblog.testblog_post'),
        ),
        migrations.AlterField(
            model_name='testblog_post',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testblog.Category'),
        ),
    ]
