# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0009_auto_20180429_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='testblog',
        ),
        migrations.AlterField(
            model_name='testblog_post',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testblog.Category'),
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
